#! /usr/bin/perl

use strict;
use warnings;
use Net::DNS;

# I can't be arsed to rewrite or even copy and paste the find-configured-domains
# code from here:
my $websitesScript = "/home/avi/bin/work/katflap/websites";

my $ifconfig = "/sbin/ifconfig";

# Some arrays for input and output. IPs are stored as a hash so I can easily
# grep it.
my(@inactive,@active,@error);
my %ips = &getIPs;
my %sites = &getConfiguredSites;

my $resolver = Net::DNS::Resolver->new;

foreach(keys(%sites)){
	my $site = $_;
	my $query = $resolver->search($site);
	if ($query){
		foreach my $rr ($query->answer){
			next unless $rr->type eq "A";
			my $Arecord = $rr->address;
			if($ips{$Arecord}){
				push(@active,$site);
			}else{
				push(@inactive,[$site, $Arecord]);
			}
		}
	}else{
		push(@error,[$site, $resolver->errorstring]);
	}
}

print "Point here:\n";
foreach(@active){
	print "\t$_\n";
}
print "Don't point here:\n";
foreach(@inactive){
	print "\t$$_[0]\t($$_[1])\n";
}
print "Errored:\n";
foreach(@error){
	print "\t$$_[0]\t($$_[1])\n";
}

sub getIPs() {
	my %ips;
	my $ifconfigCMD = "$ifconfig -a";
	foreach(`$ifconfigCMD`){
		if (/inet addr:(\S+)/){
			my $ip = $1;
			$ips{$ip} = ":)";
		}
	}
	return %ips;
}

sub getConfiguredSites(){
	my $websitesScriptError = "I need Avi's 'websites' katflap script.\nI'm currently looking for it at $websitesScript\nYou can probably get it by doing:\n\nwget https://github.com/BigRedS/work/raw/master/katflap/websites -O$websitesScript && chmod +x $websitesScript\n\nThe path is configured at approximately line 9";
	unless (-x $websitesScript){
		print $websitesScriptError;
		exit 1;
	}
	my %sites;
	foreach(`$websitesScript`){
		if (/.*\:\s*(.+)\n/){
			my $site = $1;
			$sites{$site} = ":)";
		}
	}
	return %sites;
}
