#! /usr/bin/perl

use strict;
use 5.010;

use Net::SSL;	# libcrypt-ssleay-perl

my $host = $ARGV[0];
my $port = $ARGV[1];
if ($host =~ /:/){
	$host,$port = split(/:/, $host);
}


my $socket = Net::SSL->new(
	PeerAddr => $host,
	PeerPort => $port,
	SSL_Debug => 0,
	Timeout => 15,
);

if($@){
	say "Error initiating SSL connection:";
	say $@;
}

my $cert = $socket->get_peer_certificate;
my $issuer = $cert->issuer_name;
if ($issuer =~ /\/O=([\w\s\,\.]+)\/OU/){
	$issuer = $1;
}

say "host    $host:$port";
say "cipher  ".$socket->get_cipher;
say "issuer  ".$issuer;
say "starts  ".$cert->not_before;
say "expires ".$cert->not_after;
